# Configure 'Statefulset' of mysql server
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mysql
  labels:
    app: mysql
    tier: database
spec:
  replicas: 1
  serviceName: "mysql"
  selector: # mysql Pod Should contain same labels 
    matchLabels:
      app: mysql
      tier: database
  template:
    metadata:
      labels: # Must match 'Service' and 'Deployment' selectors
        app: mysql
        tier: database
    spec:
      terminationGracePeriodSeconds: 10
      containers: 
      - image: mysql:5.7 # image from docker-hub
        args:
          - "--ignore-db-dir=lost+found" 
        name: mysql 
        env:
        - name: MYSQL_ROOT_PASSWORD # Getting Root Password  From a 'Secret'
          valueFrom:
            secretKeyRef:
              name: db-root-credentials # Name of the 'Secret'
              key: password   # 'key' inside the Secret which contains required 'value'
        - name: MYSQL_USER # Getting  username  mysql From a 'Secret'
          valueFrom:
            secretKeyRef:
              name: db-credentials
              key: username
        - name: MYSQL_PASSWORD # Getting  Password  mysql From a 'Secret'
          valueFrom:
            secretKeyRef:
              name: db-credentials
              key: password
        - name: MYSQL_DATABASE # Getting DB_Name from a 'ConfigMap'
          valueFrom:
            configMapKeyRef:
              name: db-conf
              key: name
        resources:
            limits:
              cpu: "100m"
            requests:
              cpu: "100m"
        ports:
        - containerPort: 3306
          name: mysql
        volumeMounts:        
        - name: mysql-persistent-storage
          mountPath: /var/lib/mysql 
      volumes:
      - name: mysql-persistent-storage 
        persistentVolumeClaim:
          claimName: mysql-pv-claim-2
