apiVersion: v1
kind: Secret
metadata:
  name: db-credentials
data:
 username: {{ .Values.database.username | required "database username required" | b64enc | quote }}
 password: {{ .Values.database.password | required "database password required" | b64enc | quote }}
---
apiVersion: v1
kind: Secret
metadata:
  name: db-root-credentials
data:
 password: {{ .Values.database.rootpassword}}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: db-conf
data:
 host: {{ .Values.database.host}}
 name: {{ .Values.database.dbname}}

