---
apiVersion: v1
kind: Service
metadata:
  name: mysql  
  labels:
    app: mysql
    tier: database
spec:
  ports:
    - port: 3306
      targetPort: 3306
  selector:       
    app: mysql
    tier: database
  clusterIP: None  
---
apiVersion: v1
kind: Service
metadata:
  name: python-web-app
spec:
  selector:
    app: flask-web
  ports:
    - port: 5000
      targetPort: 5000
  type: NodePort

